
services:
  admin:
    build: ./apps/admin
    container_name: commercium-admin
    ports:
      - "5173:5173"
    volumes:
      - ./apps/admin:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
    networks:
      - commercium

  web:
    build: ./apps/web
    container_name: commercium-web
    ports:
      - "5174:5173"
    volumes:
      - ./apps/web:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
    networks:
      - commercium

  api:
    build: ./apps/api
    container_name: commercium-api
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - commercium

  db:
    image: postgres:15
    container_name: commercium-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: commercium
      POSTGRES_PASSWORD: sacresecret
      POSTGRES_DB: commercium_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - commercium

volumes:
  pgdata:

networks:
  commercium:
    driver: bridge

